# render.yaml
services:
  - type: web
    name: celestiax-backend
    env: rust
    buildCommand: "cargo build --release"
    startCommand: "cargo run --release"
    plan: free # Change to a paid plan if needed
    envVars:
      - key: REDIS_URL
        value: <your_redis_url> # Replace with your Redis connection string
      - key: PORT
        value: 8080 # Render dynamically assigns a port; this is default
